# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef2eb3129b2e24ae0385e23d78f69c765a350ec3f99c30961e5b5149738a3b3940019fea8b71124262885a3bd5c4a6cf2f90dd3109b79112b43c51ffb38c5ac

test:
  secret_key_base: cb566bd9f5e3f9833f316a5ded492097101e171591eb88b4e39fb50f369fa095f1e25aca87e967da7cfffe8841063f510deffbab8c7498c7b9fd20f7b74aeb36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
